import type {
  AssemblyDef,
  Connector,
  ConnectorKind,
  MateDef,
  PartDef,
  StepDef,
  Vec3,
} from '../engine/types';

/**
 * A large worked assembly: a 14-bay modular equipment rack.
 *
 * Where `gearbox.ts` is small enough to read at a glance, this one exists to
 * exercise the app *at scale* — ~110 parts, a 45-step dependency graph, handed
 * rail pairs on every bay, keep-out volumes for cable management, and enough
 * geometry to stress the renderer, the exploded view, and the full-build
 * animation. It is generated by a small joint helper rather than hand-authored,
 * which keeps every mate geometrically exact: parts are axis-aligned (identity
 * rotation), so a connector's world frame is just `target + local`, and each
 * joint places the two mating connectors at one coincident point with
 * anti-parallel axes. That guarantees a clean, in-tolerance fit at nominal for
 * all 110 parts without hand-tuning any of them.
 *
 * Frame: Y up, metres, origin centred on the rack floor. Front is -Z.
 */

const mm = (n: number): number => n / 1000;
const I: [number, number, number, number] = [0, 0, 0, 1];

// Rack envelope.
const W = 0.6; // width (X)
const D = 0.8; // depth (Z)
const POST_H = 2.2; // upright height
const LEVELS = 14;
const PITCH = 0.13; // vertical bay pitch
const Y0 = 0.16; // first bay height above the base plate

type Corner = 'fl' | 'fr' | 'rl' | 'rr';
const CORNERS: Corner[] = ['fl', 'fr', 'rl', 'rr'];
const cornerX = (c: Corner): number => (c === 'fl' || c === 'rl' ? -W / 2 : W / 2);
const cornerZ = (c: Corner): number => (c === 'fl' || c === 'fr' ? -D / 2 : D / 2);

/**
 * Accumulates parts, connectors, mates and steps while keeping the connector
 * bookkeeping consistent. `joint` is the workhorse: give it a world point and a
 * world insertion axis and it fabricates the matching connector on each side.
 */
class RackBuilder {
  private parts = new Map<string, PartDef>();
  private connectors = new Map<string, Connector[]>();
  mates: MateDef[] = [];
  steps: StepDef[] = [];
  private jointSeq = 0;

  addPart(part: Omit<PartDef, 'connectors'>): void {
    this.parts.set(part.id, { ...part, connectors: [] });
    if (!this.connectors.has(part.id)) this.connectors.set(part.id, []);
  }

  private perp(axis: Vec3): Vec3 {
    // A stable up vector for the connector frame; roll is left free on structural
    // joints anyway, so its exact value only needs to be perpendicular-ish.
    return Math.abs(axis[1]) > 0.9 ? [0, 0, 1] : [0, 1, 0];
  }

  private push(partId: string, connector: Connector): void {
    const list = this.connectors.get(partId);
    if (!list) throw new Error(`joint references unknown part ${partId}`);
    list.push(connector);
  }

  /**
   * Create a mate between an already-placed `fixedId` and the moving `movingId`.
   * `worldPoint` is where the joint sits at nominal; `worldAxis` is the moving
   * part's insertion direction. Both connectors are derived from the parts'
   * target positions (identity rotation assumed).
   */
  joint(
    movingId: string,
    fixedId: string,
    worldPoint: Vec3,
    worldAxis: Vec3,
    opts: {
      type?: MateDef['type'];
      depth?: number;
      movingKind?: ConnectorKind;
      fixedKind?: ConnectorKind;
      symmetry?: number;
    } = {},
  ): void {
    const moving = this.parts.get(movingId);
    const fixed = this.parts.get(fixedId);
    if (!moving || !fixed) throw new Error(`joint between missing parts ${movingId}/${fixedId}`);
    const id = `j${this.jointSeq++}`;

    const mAxis = worldAxis;
    const fAxis: Vec3 = [-worldAxis[0], -worldAxis[1], -worldAxis[2]];
    const up = this.perp(worldAxis);

    const mConn: Connector = {
      id: `${id}-m`,
      kind: opts.movingKind ?? 'connectorMale',
      position: sub(worldPoint, moving.targetPose.position),
      axis: mAxis,
      up,
      accepts: [opts.fixedKind ?? 'connectorFemale'],
      symmetry: opts.symmetry ?? -1, // free roll on structural joints
      engagementDepth: opts.depth,
    };
    const fConn: Connector = {
      id: `${id}-f`,
      kind: opts.fixedKind ?? 'connectorFemale',
      position: sub(worldPoint, fixed.targetPose.position),
      axis: fAxis,
      up: this.perp(fAxis),
      accepts: [opts.movingKind ?? 'connectorMale'],
      symmetry: -1,
      engagementDepth: opts.depth,
    };
    this.push(movingId, mConn);
    this.push(fixedId, fConn);
    this.mates.push({
      id,
      a: { partId: movingId, connectorId: mConn.id },
      b: { partId: fixedId, connectorId: fConn.id },
      type: opts.type ?? 'insert',
    });
  }

  addStep(step: StepDef): void {
    this.steps.push(step);
  }

  /** Finalise: fold accumulated connectors back onto their parts. */
  build(): PartDef[] {
    return [...this.parts.values()].map((p) => ({
      ...p,
      connectors: this.connectors.get(p.id) ?? [],
    }));
  }
}

const sub = (a: Vec3, b: Vec3): Vec3 => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];

function buildRack(): AssemblyDef {
  const b = new RackBuilder();

  // ----- Base plate (the datum) -----
  b.addPart({
    id: 'baseplate',
    name: 'Base plate',
    sku: 'RK-000',
    mesh: { type: 'plate', size: [W + 0.06, 0.03, D + 0.06] },
    material: { color: '#3f4854', metalness: 0.6, roughness: 0.5 },
    targetPose: { position: [0, 0.015, 0], rotation: I },
    approach: [0, -1, 0],
    massKg: 9,
  });

  // ----- Uprights -----
  for (const c of CORNERS) {
    const x = cornerX(c);
    const z = cornerZ(c);
    b.addPart({
      id: `post-${c}`,
      name: `Upright ${c.toUpperCase()}`,
      sku: 'RK-010',
      mesh: { type: 'box', size: [0.05, POST_H, 0.05] },
      material: { color: '#5b6472', metalness: 0.55, roughness: 0.45 },
      targetPose: { position: [x, POST_H / 2 + 0.03, z], rotation: I },
      approach: [0, 1, 0],
      groupId: 'frame',
      massKg: 6,
    });
    b.joint(`post-${c}`, 'baseplate', [x, 0.03, z], [0, -1, 0], {
      depth: mm(30),
      movingKind: 'pin',
      fixedKind: 'socket',
    });
  }

  // ----- Top frame -----
  b.addPart({
    id: 'topframe',
    name: 'Top frame',
    sku: 'RK-020',
    mesh: { type: 'plate', size: [W + 0.05, 0.04, D + 0.05] },
    material: { color: '#5b6472', metalness: 0.55, roughness: 0.45 },
    targetPose: { position: [0, POST_H + 0.03 + 0.02, 0], rotation: I },
    approach: [0, 1, 0],
    groupId: 'frame',
    massKg: 7,
  });
  for (const c of CORNERS) {
    b.joint('topframe', `post-${c}`, [cornerX(c), POST_H + 0.03, cornerZ(c)], [0, -1, 0], {
      depth: mm(20),
      movingKind: 'connectorMale',
      fixedKind: 'connectorFemale',
    });
  }

  // ----- Bays: rails, module, bolts -----
  for (let i = 0; i < LEVELS; i++) {
    const y = Y0 + i * PITCH;
    const lvl = String(i + 1).padStart(2, '0');

    // Handed rail pair. Left rail spans the two left posts; right the two right.
    for (const side of ['L', 'R'] as const) {
      const x = side === 'L' ? -W / 2 + 0.03 : W / 2 - 0.03;
      const id = `rail-${lvl}-${side}`;
      b.addPart({
        id,
        name: `Mounting rail ${lvl} ${side === 'L' ? 'LEFT' : 'RIGHT'}`,
        sku: side === 'L' ? 'RK-100L' : 'RK-100R',
        mesh: { type: 'box', size: [0.02, 0.03, D - 0.08] },
        material: { color: '#8a94a6', metalness: 0.6, roughness: 0.4 },
        targetPose: { position: [x, y, 0], rotation: I },
        approach: [side === 'L' ? -1 : 1, 0, 0],
        groupId: `bay-${lvl}`,
        // Left/right rails are mirror images — the swap trap, per bay.
        mirrorGroup: `rail-${lvl}`,
        massKg: 0.4,
      });
      const frontPost = side === 'L' ? 'post-fl' : 'post-fr';
      const rearPost = side === 'L' ? 'post-rl' : 'post-rr';
      b.joint(id, frontPost, [x, y, -D / 2], [0, 0, -1], { type: 'slide', depth: mm(15) });
      b.joint(id, rearPost, [x, y, D / 2], [0, 0, 1], { type: 'slide', depth: mm(15) });
    }

    // Equipment module slides in on the rail pair.
    const modId = `module-${lvl}`;
    const modH = 0.1;
    b.addPart({
      id: modId,
      name: `Equipment module ${lvl}`,
      sku: 'RK-200',
      mesh: { type: 'box', size: [W - 0.1, modH, D - 0.12] },
      material: { color: '#c9a227', metalness: 0.4, roughness: 0.5 },
      targetPose: { position: [0, y + 0.03, 0], rotation: I },
      approach: [0, 0, -1],
      groupId: `bay-${lvl}`,
      massKg: 3.2,
    });
    b.joint(modId, `rail-${lvl}-L`, [-W / 2 + 0.04, y + 0.02, 0], [-1, 0, 0], { type: 'slide', depth: mm(10) });
    b.joint(modId, `rail-${lvl}-R`, [W / 2 - 0.04, y + 0.02, 0], [1, 0, 0], { type: 'slide', depth: mm(10) });

    // Four cage bolts securing the module to the rails.
    const boltCorners: [number, number][] = [
      [-W / 2 + 0.05, -D / 2 + 0.08],
      [W / 2 - 0.05, -D / 2 + 0.08],
      [-W / 2 + 0.05, D / 2 - 0.08],
      [W / 2 - 0.05, D / 2 - 0.08],
    ];
    boltCorners.forEach(([bx, bz], k) => {
      const boltId = `bolt-${lvl}-${k}`;
      b.addPart({
        id: boltId,
        name: `Cage bolt ${lvl}.${k + 1}`,
        sku: 'RK-500',
        mesh: { type: 'cylinder', radius: mm(3), height: mm(20) },
        material: { color: '#2f3542', metalness: 0.8, roughness: 0.3 },
        targetPose: { position: [bx, y + 0.03 + modH / 2 + mm(10), bz], rotation: I },
        approach: [0, 1, 0],
        groupId: 'fasteners',
        torqueSpecNm: 4,
        massKg: 0.02,
      });
      b.joint(boltId, modId, [bx, y + 0.03 + modH / 2, bz], [0, -1, 0], {
        type: 'bolt',
        depth: mm(10),
        movingKind: 'boltHole',
        fixedKind: 'threadedBoss',
        symmetry: 6,
      });
    });
  }

  // ----- Enclosure panels (installed last) -----
  const panels: { id: string; name: string; size: Vec3; pos: Vec3; approach: Vec3 }[] = [
    { id: 'panel-left', name: 'Side panel LEFT', size: [0.01, POST_H - 0.1, D - 0.02], pos: [-W / 2 - 0.005, POST_H / 2 + 0.03, 0], approach: [-1, 0, 0] },
    { id: 'panel-right', name: 'Side panel RIGHT', size: [0.01, POST_H - 0.1, D - 0.02], pos: [W / 2 + 0.005, POST_H / 2 + 0.03, 0], approach: [1, 0, 0] },
    { id: 'panel-rear', name: 'Rear panel', size: [W - 0.02, POST_H - 0.1, 0.01], pos: [0, POST_H / 2 + 0.03, D / 2 + 0.005], approach: [0, 0, 1] },
    { id: 'panel-door', name: 'Front door', size: [W - 0.02, POST_H - 0.1, 0.01], pos: [0, POST_H / 2 + 0.03, -D / 2 - 0.005], approach: [0, 0, -1] },
  ];
  for (const p of panels) {
    b.addPart({
      id: p.id,
      name: p.name,
      sku: 'RK-300',
      mesh: { type: 'box', size: p.size },
      material: { color: '#7d8794', metalness: 0.3, roughness: 0.6, opacity: 0.55 },
      targetPose: { position: p.pos, rotation: I },
      approach: p.approach,
      groupId: 'enclosure',
      massKg: 2,
    });
    // Each panel clips to the top frame at its mid-top.
    b.joint(p.id, 'topframe', [p.pos[0], POST_H - 0.05, p.pos[2]], [0, 1, 0], { depth: mm(8) });
  }

  // ----- Steps (the build DAG) -----
  const boltStepIds: string[] = [];
  b.addStep({
    id: 's-base',
    title: 'Set base plate',
    instruction: 'Level the base plate on the floor and lock the castors.',
    partIds: ['baseplate'],
    requires: [],
    mates: [],
    durationEstS: 90,
  });
  b.addStep({
    id: 's-posts',
    title: 'Erect uprights',
    instruction: 'Stand all four uprights into the base sockets. Check plumb before proceeding.',
    partIds: CORNERS.map((c) => `post-${c}`),
    requires: ['s-base'],
    mates: b.mates.filter((m) => m.a.partId.startsWith('post-')),
    durationEstS: 300,
    caution: 'Uprights are tall and unstable until the top frame ties them.',
  });
  b.addStep({
    id: 's-top',
    title: 'Fit top frame',
    instruction: 'Drop the top frame onto the four uprights and secure.',
    partIds: ['topframe'],
    requires: ['s-posts'],
    mates: b.mates.filter((m) => m.a.partId === 'topframe'),
    durationEstS: 180,
  });

  for (let i = 0; i < LEVELS; i++) {
    const lvl = String(i + 1).padStart(2, '0');
    const railIds = [`rail-${lvl}-L`, `rail-${lvl}-R`];
    const modId = `module-${lvl}`;
    const boltIds = [0, 1, 2, 3].map((k) => `bolt-${lvl}-${k}`);

    b.addStep({
      id: `s-rails-${lvl}`,
      title: `Bay ${lvl}: mounting rails`,
      instruction: `Fit the LEFT rail on the left uprights and the RIGHT rail on the right. The rails are handed — check the L/R stamp.`,
      partIds: railIds,
      requires: ['s-posts'],
      mates: b.mates.filter((m) => railIds.includes(m.a.partId)),
      durationEstS: 120,
      caution: 'Left/right rails look alike but mount the module the wrong way up if swapped.',
    });
    b.addStep({
      id: `s-mod-${lvl}`,
      title: `Bay ${lvl}: equipment module`,
      instruction: `Slide equipment module ${lvl} in on the rails until it seats fully at the back.`,
      partIds: [modId],
      requires: [`s-rails-${lvl}`],
      mates: b.mates.filter((m) => m.a.partId === modId),
      durationEstS: 150,
    });
    b.addStep({
      id: `s-bolts-${lvl}`,
      title: `Bay ${lvl}: secure module`,
      instruction: `Fit and torque the four cage bolts to 4 Nm.`,
      partIds: boltIds,
      requires: [`s-mod-${lvl}`],
      mates: b.mates.filter((m) => boltIds.includes(m.a.partId)),
      toolIds: ['t-driver'],
      durationEstS: 120,
    });
    boltStepIds.push(`s-bolts-${lvl}`);
  }

  b.addStep({
    id: 's-panels',
    title: 'Fit enclosure panels',
    instruction: 'Hang the side, rear and front panels once every bay is populated and secured.',
    partIds: panels.map((p) => p.id),
    requires: ['s-top', ...boltStepIds],
    mates: b.mates.filter((m) => m.a.partId.startsWith('panel-')),
    durationEstS: 240,
    caution: 'Do not block the rear cable channel keep-out with the rear panel fixings.',
  });

  return {
    id: 'equipment-rack',
    name: 'Modular Equipment Rack (14-bay)',
    revision: 'A',
    sourceUnits: 'mm',
    defaultTolerance: { positionMm: 2.5, angleDeg: 2.0, warnPositionMm: 1.6, warnAngleDeg: 1.2 },
    marker: {
      id: 'rack-datum',
      sizeM: mm(120),
      poseInAssembly: { position: [-W / 2 - 0.07, mm(60), -D / 2], rotation: I },
    },
    datums: [
      { id: 'd0', label: 'Base front-left', position: [-W / 2, 0.03, -D / 2] },
      { id: 'd1', label: 'Base front-right', position: [W / 2, 0.03, -D / 2] },
      { id: 'd2', label: 'Base rear-left', position: [-W / 2, 0.03, D / 2] },
      { id: 'd3', label: 'Top front-left', position: [-W / 2, POST_H, -D / 2] },
    ],
    parts: b.build(),
    steps: b.steps,
    background: [
      {
        id: 'floor',
        name: 'Floor',
        mesh: { type: 'box', size: [3, 0.02, 3] },
        pose: { position: [0, -0.01, 0], rotation: I },
        role: 'occluder',
      },
      {
        id: 'wall',
        name: 'Rear wall',
        mesh: { type: 'box', size: [3, 2.6, 0.02] },
        pose: { position: [0, 1.3, D / 2 + 0.25], rotation: I },
        role: 'occluder',
      },
      {
        id: 'cable-channel',
        name: 'Rear cable channel',
        mesh: { type: 'box', size: [W - 0.05, POST_H - 0.1, 0.06] },
        pose: { position: [0, POST_H / 2, D / 2 - 0.02], rotation: I },
        role: 'keepOut',
      },
    ],
    tools: [
      { id: 't-driver', name: 'Cordless driver', note: 'Cage bolts — 4 Nm, do not overtighten the cage nut.' },
      { id: 't-level', name: 'Spirit level', note: 'Plumb the uprights before the top frame goes on.' },
    ],
  };
}

export const equipmentRack: AssemblyDef = buildRack();
